services:

  db:
    container_name: is-db
    build: docker/images/db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  rpc-server:
    container_name: is-rpc-server
    build: docker/images/python
    volumes:
      - "./src/rpc-server:/usr/src/app"
    depends_on:
      - db

  rpc-client:
    container_name: is-rpc-client
    build: docker/images/python
    volumes:
      - "./src/rpc-client:/usr/src/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - rpc-server

  sample-db-access:
    container_name: is-db-access
    build: docker/images/python
    volumes:
      - "./src/samples/db-access:/usr/src/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - rpc-server

  sample-xml-generation:
    container_name: is-xml-generation
    build: docker/images/python
    volumes:
      - "./src/samples/xml-generation:/usr/src/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - rpc-server

volumes:
  postgres_data: