services:
  db:
    container_name: is-db
    build: docker/images/db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  db-rel:
      container_name: is-db-rel
      build: docker/images/db-rel
      volumes:
        - postgres_rel_data:/var/lib/postgresql/data/
      ports:
      - "5433:5432"
      
  rpc-server:
    container_name: is-rpc-server
    build: docker/images/python
    volumes:
      - "./src/rpc-server:/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - db

  rpc-client:
    container_name: is-rpc-client
    build: docker/images/python
    volumes:
      - "./src/rpc-client:/app"
      - "./docker/volumes/data:/data"
    depends_on:
      - rpc-server

volumes:
  postgres_data:
  postgres_rel_data:
